# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('clazz_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('clazz_name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('entrance', models.DateField()),
                ('graduation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('teach_year', models.DateField()),
                ('term', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('clazz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Clazz')),
            ],
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('is_overtime', models.BooleanField(default=False)),
                ('file_path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('sex', models.IntegerField(choices=[(0, 'female'), (1, 'male')], default=1)),
                ('clazz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Clazz')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('last_time', models.DateTimeField()),
                ('issue_time', models.DateTimeField(auto_now_add=True)),
                ('begin_remind', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=50)),
                ('sex', models.IntegerField(choices=[(0, 'female'), (1, 'male')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(0, 'admin'), (1, 'teacher'), (2, 'student'), (3, 'guest')], default=3)),
                ('role_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('validate_code', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='finish',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Student'),
        ),
        migrations.AddField(
            model_name='finish',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Task'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Teacher'),
        ),
    ]
