# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz_id', models.CharField(max_length=20)),
                ('clazz_name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('entrance', models.DateField()),
                ('graduation', models.DateField()),
            ],
        ),
    ]
