# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clazz',
            name='id',
        ),
        migrations.AlterField(
            model_name='clazz',
            name='clazz_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
