# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0002_auto_20170403_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('teach_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('sex', models.IntegerField(choices=[(0, 'female'), (1, 'male')], default=1)),
                ('clazz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Clazz')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=50)),
                ('sex', models.IntegerField(choices=[(0, 'female'), (1, 'male')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(0, 'admin'), (1, 'teacher'), (2, 'student'), (3, 'guest')], default=3)),
                ('role_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('register_time', models.DateTimeField()),
                ('validate_code', models.CharField(max_length=32)),
            ],
        ),
    ]
